---
- name: oVirt ansible collection
  hosts: localhost
  connection: local
  collections:
    - ovirt.ovirt
  vars_files:
    - vault.yml

  vars:
    vms:
      - name: c7_test1
  #      cluster: Support
        template: CentOS-7-x86_64-GenericCloud-2003
        cores: 2
        memory: 4GiB
        nics:
          - name: eth0
            network: Lab
        disks:
          - name: CentOS-7-x86_64-GenericCloud-2003
            size: 30GiB
            name_prefix: false
            interface: virtio_iscsi
        type: server
        cloud_init:
          dns_servers: '8.8.8.8 8.8.4.4'
          host_name: c7_test1.example.com
          custom_script: |
            users:
              - name: ansible
                groups: wheel
        cloud_init_nics:
          - nic_name: eth0
            nic_boot_protocol: static
            nic_ip_address: 172.22.4.66
            nic_netmask: 255.255.255.0
            nic_gateway: 172.22.4.1
            nic_on_boot: True

  tasks:
    - block:
        - name: Obtain SSO token with using username/password credentials
          ovirt.ovirt.ovirt_auth:
            url: https://testengine.lab.home.gatwards.org/ovirt-engine/api
            username: admin@internal
            password: "{{ vault_ovirt_admin_password }}"

        - import_role:
            name: ovirt.ovirt.vm_infra

      always:
        - name: Always revoke the SSO token
          ovirt_auth:
            state: absent
            ovirt_auth: "{{ ovirt_auth }}"
