---
- name: Setup oVirt storage
  hosts: localhost
  connection: local
  collections:
    - ovirt.ovirt
  vars_files:
    - vault.yml

  tasks:
    - block:
        - name: Obtain SSO token with using username/password credentials
          ovirt.ovirt.ovirt_auth:
            url: https://testengine.lab.home.gatwards.org/ovirt-engine/api
            username: admin@internal
            password: "{{ vault_ovirt_admin_password }}"

        - name: set up VMstore domain
          ovirt_storage_domain:
            auth: "{{ ovirt_auth }}"
            name: VMstore
            host: baremetal2.lab.home.gatwards.org
            data_center: Support
            nfs:
              address: 172.22.1.240
              path: /volume1/testnfs2/vmstore
              version: v3


      always:
        - name: Always revoke the SSO token
          ovirt_auth:
            state: absent
            ovirt_auth: "{{ ovirt_auth }}"
