---
- name: oVirt ansible collection
  hosts: localhost
  connection: local
  collections:
    - ovirt.ovirt
  vars_files:
    - vault.yml
  vars:
    ovirt_hosts:
    - host: baremetal2.lab.home.gatwards.org
      address: 172.22.4.12
    - host: baremetal5.lab.home.gatwards.org
      address: 172.22.4.15

  tasks:
    - block:
        - name: Obtain SSO token with using username/password credentials
          ovirt.ovirt.ovirt_auth:
            url: https://testengine.lab.home.gatwards.org/ovirt-engine/api
            username: admin@internal
            password: "{{ vault_ovirt_admin_password }}"


        - name: Set empty arrays
          set_fact:
            a_list: []
            b_list: []

        - name: Add A hosts to A
          set_fact:
            a_list: "{{ a_list + [ item.host ] }}"
          with_items:
          - "{{ ovirt_hosts }}"
          when: '"baremetal2" in item.host'

        - name: Add B hosts to B
          set_fact:
            b_list: "{{ b_list + [ item.host ] }}"
          with_items:
          - "{{ ovirt_hosts }}"
          when: '"baremetal5" in item.host'


        - name: Create and assign affinity group to VMs a-vm1 and a-vm2 with a-host1 and a-host2
          ovirt_affinity_group:
            auth: "{{ ovirt_auth }}"
            name: az-a
            cluster: Support
            vm_enforcing: false      # False allows VM to start even if hosts cannot be met
            vm_rule: positive
            host_enforcing: false    # False will allow hosts not listed to be used if needed
            host_rule: positive
            vms: []
            hosts: "{{ a_list }}"


        - name: Create and assign affinity group to VMs b-vm1 and b-vm2 with b-host1 and b-host2
          ovirt_affinity_group:
            auth: "{{ ovirt_auth }}"
            name: az-b
            cluster: Support
            vm_enforcing: false
            vm_rule: positive
            host_enforcing: false
            host_rule: positive
            vms: []
            hosts: "{{ b_list }}"




      always:
        - name: Always revoke the SSO token
          ovirt_auth:
            state: absent
            ovirt_auth: "{{ ovirt_auth }}"
